[package]
name = "sysmon_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.24"
crossterm = "0.27"
sysinfo = { version = "0.29", features = ["refresh_cpu", "refresh_memory"] }
tokio = { version = "1", features = ["full"] }
